List<String> getLyrics() {
  return [
    'Hace un tiempo no duermo con vos',
    'Pienso cómo todo se desgastó',
    'Te siento un poco má rara,',
    'Ya no te provoco nada',
    'Siento más grande la cama,', 
    '¿qué es lo que pasó?',
    'Quisiera cumplir tus expectativas',
    'No puedo fingir lo que no soy',
    'Sueño que algún día quiera ser mía',
    'Pero exige todo menos amor',
    'Juro que no quiero nada pero cuando', 
    'se me acerca quiero to',
    'Ya no quiero lastimarme y chocar dos',
    'veces el mismo paredón',
    'Quiero de ese veneno que me envenenó',
    'Soy el perdedor de los dos, de los', 
    'do-oh-oh',
    'Baby, dímelo, oh-oh, ¿qué fue que pasó',
    'oh-oh?',
    'Entre nosotros do-oh-oh algo se rompió,',
    'oh-oh',
    'No me hables de amo-o-or',
    'si mi corazó-ó-ón',
    'Jamás te importó, no, no',
    'Baby, dímelo, oh-oh, ¿qué fue que pasó,',
    'oh-oh?',
    'Entre nosotros do-oh-oh algo se rompió,',
    'oh-oh',
    'No me hables de amo-o-or',
    'si mi corazó-ó-ón',
    'Jamás te importó, no, no',
    'Dije que no iba a lastimarte,',
    'lo volví a hacer',
    'Siempre que me pongo a pensarte',
    'se larga a llover',
    'Me cansé de escribir tu nombre',
    'en la hoja de un papel',
    'No queremo, pero no hacemos mal',
    '(no queremo, pero no hacemos mal)',
    'Y eso molesta',
    'No se da cuenta que me hiere cuando',
    'la llamo y no contesta',
    'Del amor al odio, noche de insomnio',
    'buscando respuestas',
    'Yo ya me sé esa jugada, no me mientas',
    'en la cara (no), no, no, no',
    'El que las hace las paga y el karma',
    'ya tiene una deuda contigo y eso yo lo sé',
    'Que estás cansada de verme perdido,',
    'no tiene sentido intentarlo otra vez',
    'No me repitas algo que ya sé, incontable',
    'las vece que fallé',
    'No fuiste tú, yo también te lloré',
    'pero aprendí y después te solté',
    'Baby, dímelo, oh-oh, ¿qué fue que pasó, oh-oh?',
    'Entre nosotros do-oh-oh algo se rompió, oh-oh',
    'No me hables de amo-o-or si mi corazó-ó-ón',
    'Jamás te importó, no, no',
    'Baby, dímelo, oh-oh, ¿qué fue que pasó, oh-oh?',
    'Entre nosotros do-oh-oh algo se rompió, oh-oh',
    'No me hables de amo-o-or si mi corazó-ó-ón',
    'Jamás te importó, no, no, no, no'
  ];
}